# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
verbosity = 3
fs_permissions = [{ access = "read-write", path = "./"}] # to write logs into a local `./test.txt` file

[rpc_endpoints]
local = "http://localhost:8545"
gnosis = "https://provider-proxy.hoprnet.workers.dev/xdai_mainnet"
goerli = "https://provider-proxy.hoprnet.workers.dev/eth_goerli"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
gnosis = { key = "${GNOSISSCAN_API_KEY}", url = "https://gnosisscan.io" }

# testing and local network
[profile.development]
eth_rpc_url = "http://localhost:8545" # cannot directly use profile.default.rpc_endpoints.local

# staging environment
[profile.staging]
eth_rpc_url = "https://provider-proxy.hoprnet.workers.dev/eth_goerli"

# production environment environment
[profile.production]
eth_rpc_url = "https://provider-proxy.hoprnet.workers.dev/xdai_mainnet"