[package]
name = "core-ethereum-api"
version = "0.1.0"
authors = ["HOPR Association <tech@hoprnet.org>"]
description = "Implements the main HOPR chain interface"
edition = "2021"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm", "prometheus"]
console_error_panic_hook = ["dep:console_error_panic_hook"]
wasm = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:js-sys", "dep:serde-wasm-bindgen", "dep:gloo-timers",
    "core-ethereum-db/wasm", "core-ethereum-misc/wasm", "core-ethereum-actions/wasm",
    "core-crypto/wasm", "core-network/wasm", "core-strategy/wasm", "core-path/wasm", "core-packet/wasm", "core-p2p/wasm", "core-protocol/wasm", "core-types/wasm",
    "utils-db/wasm", "utils-misc/wasm", "utils-log/wasm", "utils-metrics?/wasm", "utils-types/wasm", "utils-validation/wasm"
]
prometheus = ["dep:lazy_static", "dep:utils-metrics", "core-packet/prometheus", "core-protocol/prometheus", "core-strategy/prometheus"]

[dependencies]
async-std = { workspace = true }
async-trait = { workspace = true }
async-lock = { workspace = true }
futures = { workspace = true }
futures-concurrency = "7.3.0"
gloo-timers = { workspace = true, optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
lazy_static = { workspace = true, optional = true }
js-sys = { workspace = true, optional = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true, optional = true}
thiserror = { workspace = true }
validator = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }

core-network = { workspace = true, default-features = false }
core-crypto = { workspace = true, default-features = false }
core-ethereum-actions = { workspace = true, default-features = false }
core-ethereum-db = { workspace = true, default-features = false }
core-ethereum-misc = { workspace = true, default-features = false }
core-path = { workspace = true, default-features = false }
core-p2p = { workspace = true, default-features = false }
core-packet = { workspace = true, default-features = false }
core-protocol = { workspace = true, default-features = false }
core-strategy = { workspace = true, default-features = false }
core-types = { workspace = true, default-features = false }
utils-db = { workspace = true, default-features = false }
utils-log = { workspace = true, default-features = false }
utils-misc = { workspace = true, default-features = false }
utils-metrics = { workspace = true, optional = true, default-features = false }
utils-types = { workspace = true, default-features = false }
utils-validation = { workspace = true, default-features = false }


[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O', '--enable-reference-types']
