[package]
name = "core-libp2p-hopr-protocol"
version = "0.1.0"
authors = ["HOPR Association <tech@hoprnet.org>"]
edition = "2021"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm"]
wasm = ["dep:wasm-bindgen", "libp2p/wasm-bindgen", "utils-log/wasm", "utils-misc/wasm", "utils-metrics/wasm"]

[dependencies]
libp2p = { git = "https://github.com/hoprnet/rust-libp2p.git", branch = "release/providence" }

console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen = { workspace = true, optional = true }

utils-log = { path = "../../../utils/crates/utils-log", default-features = false}
utils-misc = { path = "../../../utils/crates/utils-misc", default-features = false}
utils-metrics = { path = "../../../utils/crates/utils-metrics", default-features = false }

[dev-dependencies]
more-asserts = "0.3.1"
env_logger = "0.10.0"
wasm-bindgen-test = "0.3.36"

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O', '--enable-reference-types']
