name: hopr-dev
services:
  anvil:
    image: hopr-anvil-local
    build:
      context: /Users/tbr/work/hopr/hoprnet
      dockerfile: ../../packages/ethereum/Dockerfile.anvil
      args:
        HOPR_TOOLCHAIN_IMAGE: hopr-toolchain-local
    depends_on:
      - toolchain
  hopli:
    image: hopli-local
    build:
      context: /Users/tbr/work/hopr/hoprnet
      dockerfile: ../../packages/hopli/Dockerfile
      args:
        HOPR_TOOLCHAIN_IMAGE: hopr-toolchain-local
    depends_on:
      - toolchain
  hoprd:
    image: hoprd-local
    build:
      context: /Users/tbr/work/hopr/hoprnet
      dockerfile: ../../packages/hoprd/Dockerfile
      args:
        HOPR_TOOLCHAIN_IMAGE: hopr-toolchain-local
    depends_on:
      - toolchain
  hoprd-nat:
    image: hoprd-nat-local
    build:
      context: /Users/tbr/work/hopr/hoprnet/scripts/nat
      dockerfile: ../nat/Dockerfile
      args:
        HOPR_TOOLCHAIN_IMAGE: hopr-toolchain-local
    depends_on:
      - toolchain
  pluto:
    image: hopr-pluto-local
    build:
      context: /Users/tbr/work/hopr/hoprnet
      dockerfile: ../pluto/Dockerfile
      args:
        HOPR_ANVIL_IMAGE: hopr-anvil-local
        HOPR_HOPLI_IMAGE: hopli-local
        HOPR_HOPRD_IMAGE: hoprd-local
    depends_on:
      - anvil
      - hopli
      - hoprd
  toolchain:
    image: hopr-toolchain-local
    build:
      context: /Users/tbr/work/hopr/hoprnet
      dockerfile: ../toolchain/Dockerfile
networks:
  default:
    name: hopr-dev_default
