[package]
name = "foundry-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "readidentity"
path = "src/key_pair.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4.0.28", features = ["derive", "env"] }
ethers = "1.0.2"