---
name: Build Anvil

on:
  workflow_call:
    secrets:
      GOOGLE_HOPRASSOCIATION_PROJECT:
        required: true
      GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY:
        required: true
concurrency:
  group: ${{ github.head_ref }}-anvil
  cancel-in-progress: true
jobs:

  build:
    name: docker
    runs-on: ubuntu-2-core
    steps:
      - name: Checkout hoprnet
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: auth
        name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Login Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: packages/ethereum/Dockerfile.anvil
          cache-from: type=registry,ref=europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/hopli:buildcache
          cache-to: type=registry,ref=europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/hopli:buildcache,mode=max
          tags: europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/hopli:pr-${{ github.event.pull_request.number }}
