---
name: Build Debian

on:
  pull_request:
    branches:
      - master
      - release/*
    types:
      - synchronize
      - opened
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:

  build:
    name: docker
    runs-on: ubuntu-2-core
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: curl -v http://deb.debian.org/debian/dists/bullseye/InRelease

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          file: packages/ethereum/Dockerfile.test
          tags: europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/anvil:pr-${{ github.event.pull_request.number }}
