---
# The goal of this workflow is to build the `hoprd` docker image when a pull request is created or commit push into it and has the label `deploy_nodes`
name: Check PR

on:
  pull_request:
    branches:
      - master
      - release/*
    types:
      - synchronize
      - opened
      - label
      - unlabeled

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check_pr:
    name: Check PR
    runs-on: ubuntu-latest
    # outputs:
    #   toolchain: ${{ steps.changeset.outputs.toolchain}}
    #   hopli: ${{ steps.changeset.outputs.hopli}}
    #   hoprd: ${{ steps.changeset.outputs.hoprd}}
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check PR changes
        id: check_pr_changes
        # Set outputs using the command.
        run: |
          event_type=${{ github.event.action }}
          echo "The event fired is: ${event_type}"
          set -x
          labels=${{ github.event.pull_request.labels.* }}
          label_names=${{ github.event.pull_request.labels.*.names }}
          first_label=${labels[0]}
          echo "labels: ${labels}"
          echo "label_names: ${label_names}"
          echo "first_label: ${first_label}"
          current_label=${{ github.event.label.name }}
          echo "This is the affected label: ${current_label}"
          declare params=""
          case "${event_type}" in
            synchronize | opened)
              params="${params} --event push --base-branch ${{ github.event.pull_request.base.sha }} --head-branch ${{ github.event.pull_request.head.sha }}"
              ;;
            labeled)
              params="${params} --event labeled --labels ${current_label}"
              ;;
            unlabeled)
              params="${params} --event unlabeled --labels ${current_label}"
              ;;
            *)
              echo "invalid event: ${event_type}"
              exit 1
              ;;
          esac;
          ./scripts/check-pr.sh ${params}
          cat check_pr_results.txt

