---
# The goal of this workflow is to build the `hoprd` docker image when a pull request is created or commit push into it and has the label `deploy_nodes`
name: Check PR

on:
  pull_request:
    branches:
      - master
      - release/*
    types:
      - synchronize
      - opened
      - labeled
      - unlabeled

# concurrency:
#   group: ${{ github.head_ref }}
#   cancel-in-progress: false

jobs:
  check_changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      build_toolchain: ${{ steps.check_pr_changes.outputs.build_toolchain }}
      build_hopli: ${{ steps.check_pr_changes.outputs.build_hopli }}
      build_hoprd: ${{ steps.check_pr_changes.outputs.build_hoprd }}
      create_deployment: ${{ steps.check_pr_changes.outputs.create_deployment }}
      delete_deployment: ${{ steps.check_pr_changes.outputs.delete_deployment }}
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check PR changes
        id: check_pr_changes
        # Set outputs using the command.
        run: |
          event_type=${{ github.event.action }}
          echo "The event fired is: ${event_type}"
          label_name=${{ github.event.label.name }}
          echo "This is the affected label: ${label_name}"
          declare params=""
          case "${event_type}" in
            synchronize | opened)
              params="${params} --event push --base-branch ${{ github.event.pull_request.base.sha }} --head-branch ${{ github.event.pull_request.head.sha }}"
              ;;
            labeled)
              params="${params} --event labeled --label ${label_name}"
              ;;
            unlabeled)
              params="${params} --event unlabeled --label ${label_name}"
              ;;
            *)
              echo "invalid event: ${event_type}"
              exit 1
              ;;
          esac;
          ./scripts/check-pr.sh ${params}
          cat check_pr.log >> $GITHUB_OUTPUT

  build_toolchain:
    name: Build Toolchain
    needs:
      - check_changes
    if: ${{needs.check_changes.outputs.build_toolchain }}
    uses: ./.github/workflows/build-toolchain.yaml
    secrets:
      GOOGLE_HOPRASSOCIATION_PROJECT: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
      GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      # - name: Build Toolchain docker image

      #   uses: ./.github/workflows/build-toolchain.yaml
      #   # with:
      #   #   token: ${{ secrets.access-token }}
      # - name: Build Hopli docker image
      #   if: ${{ env.build_hopli }}
      #   run: echo "Building Hopli"
      # - name: Build Hoprd docker image
      #   if: ${{ env.build_hoprd }}
      #   run: echo "Building Hoprd"
      # - name: Create Deployment
      #   if: ${{ env.create_deployment }}
      #   run: echo "Deploying nodes"
      # - name: Delete Deployment
      #   if: ${{ env.delete_deployment }}
      #   run: echo "Undeploying nodes"


