name: HOPR Generate API docs

env:
  HOPR_GITHUB_REF: ${{ github.ref }}

on:
  push:
    branches: ['**']
    paths-ignore:
      - 'docs/**/*'
      - '.processes/**/*'

jobs:
  docs:
    name: Generate API docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git info
        run: ./scripts/configure-git-info.sh

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: yarn

      - name: Install tools (only when using ACT)
        if: ${{ env.ACT == 'true' }}
        run: |
          apt update
          apt install --no-install-recommends lsof

      - name: Generate docs
        run: |
          make -j deps-ci
          make -j build-docs
        env:
          DEPLOYER_PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

      - name: Format newly created files
        run: make lint-fix

      - name: Move OpenAPI spec file into documentation directory
        run: |
          mv packages/hoprd/rest-api-v2-full-spec.json docs/hopr-documentation/
          git add docs/hopr-documentation/rest-api-v2-full-spec.json

      - name: Commit docs changes
        # only commit changes when not running via act and when on final branches
        if: |
          (github.ref == 'refs/heads/master' ||
           github.ref == 'refs/heads/avado' ||
           startsWith(github.ref, 'refs/heads/debug-docs/') ||
           startsWith(github.ref, 'refs/heads/release/')
          ) && !env.ACT
        run: ./scripts/commit-and-push-all-changes.sh
        env:
          HOPR_GIT_MSG: 'Re-generate API docs for packages'
