---
name: Draft

on:
  pull_request:
    branches:
      - master
      - release/*
      - debug-deploy/network-rotsee
    types:
      - opened
      - synchronize
concurrency:
  group: ${{ github.head_ref }}-draft
  cancel-in-progress: false
jobs:
  draft:
    name: Convert to draft
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Convert to draft
        run: gh pr ready ${{ github.event.pull_request.number }} --undo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  