---
# The goal of this workflow is to build the `hoprd` docker image when a pull request is created or commit push into it and has the label `deploy_nodes`
name: PR checks

on:
  pull_request:
    branches:
      - master
      - release/*
    types:
      - synchronize
      - opened
      - labeled
      - unlabeled

jobs:
  check_changeset:
    name: Check changeset
    runs-on: ubuntu-latest
    outputs:
      build_toolchain: ${{ steps.check_pr_changeset.outputs.build_toolchain }}
      build_hopli: ${{ steps.check_pr_changeset.outputs.build_hopli }}
      build_hoprd: ${{ steps.check_pr_changeset.outputs.build_hoprd }}
      create_deployment: ${{ steps.check_pr_changeset.outputs.create_deployment }}
      delete_deployment: ${{ steps.check_pr_changeset.outputs.delete_deployment }}
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check PR changes
        id: check_pr_changeset
        # Set outputs using the command.
        run: |
          event_type=${{ github.event.action }}
          echo "The event fired is: ${event_type}"
          label_name=${{ github.event.label.name }}
          echo "This is the affected label: ${label_name}"
          declare params=""
          case "${event_type}" in
            synchronize | opened)
              params="${params} --event push --base-branch ${{ github.event.pull_request.base.sha }} --head-branch ${{ github.event.pull_request.head.sha }}"
              ;;
            labeled)
              params="${params} --event labeled --label ${label_name}"
              ;;
            unlabeled)
              params="${params} --event unlabeled --label ${label_name}"
              ;;
            *)
              echo "invalid event: ${event_type}"
              exit 1
              ;;
          esac;
          ./scripts/check-pr.sh ${params}
          cat check_pr.log >> $GITHUB_OUTPUT
      # - name: Build Toolchain docker image
      #   run: gh workflow run build-toolchain.yaml --ref ${{ github.event.pull_request.head.ref }} -f branch=${{ github.event.pull_request.head.ref }}
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      # - name: Build Hopli docker image
      #   run: gh workflow run build-hopli.yaml --ref ${{ github.event.pull_request.head.ref }} -f branch=${{ github.event.pull_request.head.ref }}
      #   env:
      #     GH_TOKEN: ${{ github.token }}

  build_toolchain:
    name: Build Toolchain
    needs:
      - check_changeset
    if: ${{needs.check_changeset.outputs.build_toolchain }}
    uses: ./.github/workflows/build-toolchain.yaml
    secrets:
      GOOGLE_HOPRASSOCIATION_PROJECT: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
      GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

  build_hopli:
    name: Build Hopli
    needs:
      - check_changeset
    if: ${{needs.check_changeset.outputs.build_hopli }}
    uses: ./.github/workflows/build-hopli.yaml
    secrets:
      GOOGLE_HOPRASSOCIATION_PROJECT: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
      GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

  build_hoprd:
    name: Build Hoprd
    needs:
      - check_changeset
    if: ${{needs.check_changeset.outputs.build_hoprd }}
    uses: ./.github/workflows/build-hoprd.yaml
    secrets:
      GOOGLE_HOPRASSOCIATION_PROJECT: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
      GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      K8S_SSH_SERVICE_HOST: ${{ secrets.K8S_SSH_SERVICE_HOST }}
      K8S_SSH_SERVICE_USERNAME: ${{ secrets.K8S_SSH_SERVICE_USERNAME }}
      K8S_SSH_SERVICE_PASSWORD: ${{ secrets.K8S_SSH_SERVICE_PASSWORD }}
