---
name: GH Runner

on:
  pull_request:
    branches:
      - master
      - release/*
    types:
      - synchronize
      - opened
concurrency:
  group: ${{ github.head_ref }}-runner
  cancel-in-progress: true
jobs:

  build:
    name: docker
    runs-on: ubuntu-2-core
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3

      - id: auth
        name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Login Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: kubernetes
          node: ausias

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: packages/ethereum/Dockerfile.test
          cache-from: type=registry,ref=europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/anvil:buildcache-test
          cache-to: type=registry,ref=europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/anvil:buildcache-test,mode=max
          tags: europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/anvil:pr-${{ github.event.pull_request.number }}
